[package]
name = "discord-rs"
version = "0.1.1"
description = "A rust library for interacting with the Discord API in a blazingly fast way"
authors = ["Brian T. bptiburcio@gmail.com"]
edition = "2021"
rust-version = "1.70.0"
documentation = "https://docs.rs/discord-rs"
homepage = "https://discordrs.io/"
repository = "https://github.com/BrianTiburcio/discord-rs"
license-file = "LICENSE.txt"
keywords = ["discord", "discord-api", "discord-bot", "discord-webhook"]
categories = ["api-bindings"]
readme = "README.md"
exclude = [
    ".ignore/*",
    "src/examples/*",
    "target/*"
]
include = [
    "**/*.rs",
    "Cargo.toml",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
colored = "2.0.0"
dotenv = "0.15.0"
futures-util = "0.3.28"
rand = "0.8.5"
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.28.2", features = ["full"] }
tokio-tungstenite = { version = "0.19.0", features = ["native-tls"] }
tungstenite = { version = "0.19.0", features = ["native-tls"] }

[dev-dependencies]


[profile.dev]
opt-level = 0
# Dev profile settings

[profile.release]
opt-level = 3
# Release profile settings