[package]
name = "discord-rs"
description = "A rust library for interacting with the Discord API in a blazingly fast way"
authors = ["Brian Tiburcio", "bptiburcio@gmail.com"]
edition = "2021"
rust-version = "1.70.0"
version = "0.1.1"
documentation = "https://docs.rs/discord-rs"
homepage = "https://discordrs.io/"
repository = "https://github.com/BrianTiburcio/discord-rs"
license-file = "LICENSE.txt"
keywords = ["discord", "discord api", "discord bot", "discord webhook"]
categories = ["api-bindings"]
readme = "https://github.com/BrianTiburcio/discord-rs/blob/main/README.md"
exclude = [
    "target/*",
    ".ignore/*",
    "src/sample.rs"
]
include = [
    "**/*.rs",
    "Cargo.toml",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"

[dev-dependencies]
dotenv = "0.15.0"
log = "0.4.19"
tokio = { version = "1.28.2", features = ["full"] }

[profile.dev]
opt-level = 0
# Dev profile settings

[profile.release]
opt-level = 3
# Release profile settings